#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    # Setup environ
    sys.path.append(os.getcwd())
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "classclown.settings")

    # Setup django
    import django

    django.setup()
    from classifieds.search import run

    run()
